### ISSUE TITLE
A question about 'label_map' when evaluate()

### ISSUE THREAD

**Issue by tyistyler** [sinovation/ZEN2#1]
Excuse me, when I use the fine-tuned msra_ner model to fine-tune other dateset(like weibo, resume..), it return error sometimes, like  
`Traceback (most recent call last):  

File "run_token_level_ft_task.py", line 1263, in <module>
--main()
File "run_token_level_ft_task.py", line 1240, in main  
--result = evaluate(args, model, tokenizer, ngram_dict, processor, label_list, device, mode="dev")  
File "run_token_level_ft_task.py", line 976, in evaluate  
--temp_2.append(label_map[logits[i][j]])  
KeyError: 0
`  
the label_map doesn't have the key-"0", but I get it, (I dont modify the code) and my paratemers is 

`os.system("python run_token_level_ft_task.py --task_name weibo --seed 123 "
          "--do_eval --eval_test --do_lower_case --data_dir ./dataset/weibo "
          "--init_checkpoint dataset/zh_zen_base_2.0_ft_msraner --max_seq_length 128 --output_dir ./result "
          "--learning_rate 1e-5 "
          "--train_batch_size 8 --num_train_epochs 30 --warmup_proportion 0.1")`

If possible, could you check this question, thanks!!

**Comment by yuanheTian** [comment]
> Excuse me, when I use the fine-tuned msra_ner model to fine-tune other dateset(like weibo, resume..), it return error sometimes, like
> `Traceback (most recent call last):
> 
> File "run_token_level_ft_task.py", line 1263, in
> --main()
> File "run_token_level_ft_task.py", line 1240, in main
> --result = evaluate(args, model, tokenizer, ngram_dict, processor, label_list, device, mode="dev")
> File "run_token_level_ft_task.py", line 976, in evaluate
> --temp_2.append(label_map[logits[i][j]])
> KeyError: 0
> `
> the label_map doesn't have the key-"0", but I get it, (I dont modify the code) and my paratemers is
> 
> `os.system("python run_token_level_ft_task.py --task_name weibo --seed 123 " "--do_eval --eval_test --do_lower_case --data_dir ./dataset/weibo " "--init_checkpoint dataset/zh_zen_base_2.0_ft_msraner --max_seq_length 128 --output_dir ./result " "--learning_rate 1e-5 " "--train_batch_size 8 --num_train_epochs 30 --warmup_proportion 0.1")`
> 
> If possible, could you check this question, thanks!!

Thanks for letting us know!

The key "0" corresponds to the special "<PAD>" label. This error might happen in the first couple of epochs because the model is not well trained at that time. 

We updated our code and it should work well now.
